global:

templates:
- '/etc/alertmanager/*.tmpl'
# The root route on which each incoming alert enters.
route:
  # default route if none match
  receiver: alert-emailer

  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  # TODO:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1s
  repeat_interval: 1s

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.

receivers:
- name: alert-emailer
  email_configs:
  - to: 'example@example.org'
    send_resolved: false
    from: 'example@example.org'
    smarthost: 'smtp.gmail.com:587'
    auth_identity: 'example@example.org'
    auth_username: 'example@example.org'
    auth_password: 'example'
    #auth_secret: 'sender@example.com'
